name: Trigger auto deployment for container-app-fw25usgo3vzee

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-fw25usgo3vzee-AutoDeployTrigger-439c227f-cc35-46fb-923b-b193c10f381c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPFW25USGO3VZEE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPFW25USGO3VZEE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPFW25USGO3VZEE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPFW25USGO3VZEE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPFW25USGO3VZEE_REGISTRY_PASSWORD }}
          containerAppName: container-app-fw25usgo3vzee
          resourceGroup: todonodejspgsqlgoogleauthb85b8689
          imageToBuild: default/container-app-fw25usgo3vzee:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


